In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

try:
    df = pd.read_csv("diamonds.csv")
except FileNotFoundError:
    sns.load_dataset("diamonds").to_csv("diamonds.csv", index=False)   # needs internet
    df = pd.read_csv("diamonds.csv")

In [3]:
df.head()

   carat      cut color clarity  depth  table  price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75

In [6]:
print(df.shape)

(53940, 10)

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 53940 entries, 0 to 53939
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   carat    53940 non-null  float64
 1   cut      53940 non-null  str
 2   color    53940 non-null  str
 3   clarity  53940 non-null  str
 4   depth    53940 non-null  float64
 5   table    53940 non-null  float64
 6   price    53940 non-null  int64
 7   x        53940 non-null  float64
 8   y        53940 non-null  float64
 9   z        53940 non-null  float64
dtypes: float64(6), int64(1), str(3)
memory usage: 4.7 MB

In [8]:
df.describe().round(1)

         carat    depth    table    price        x        y        z
count  53940.0  53940.0  53940.0  53940.0  53940.0  53940.0  53940.0
mean       0.8     61.7     57.5   3932.8      5.7      5.7      3.5
std        0.5      1.4      2.2   3989.4      1.1      1.1      0.7
min        0.2     43.0     43.0    326.0      0.0      0.0      0.0
25%        0.4     61.0     56.0    950.0      4.7      4.7      2.9
50%        0.7     61.8     57.0   2401.0      5.7      5.7      3.5
75%        1.0     62.5     59.0   5324.2      6.5      6.5      4.0
max        5.0     79.0     95.0  18823.0     10.7     58.9     31.8

In [9]:
df.isna().sum()

carat      0
cut        0
color      0
clarity    0
depth      0
table      0
price      0
x          0
y          0
z          0
dtype: int64

In [12]:
df[["carat", "x", "y", "z"]].value_counts()

carat  x     y     z
0.30   4.28  4.31  2.67    17
       4.29  4.32  2.68    17
0.32   4.40  4.43  2.72    16
0.30   4.31  4.33  2.67    16
       4.30  4.33  2.68    15
                           ..
0.70   5.71  5.76  3.47     1
0.72   5.75  5.76  3.50     1
       5.69  5.75  3.61     1
0.86   6.15  6.12  3.74     1
0.75   5.83  5.87  3.64     1
Name: count, Length: 43552, dtype: int64